import type { PricingPackage } from '../../types/pricing';

export const pricingPackages: PricingPackage[] = [
  {
    id: 'starter',
    titleKey: 'pricing.starter.title',
    speed: '1 Mbps',
    priceKey: 'pricing.starter.price',
    featuresKeys: [
      'pricing.feature.1',
      'pricing.feature.2',
      'pricing.feature.3',
      'pricing.feature.4',
    ],
    isPopular: false,
  },
  {
    id: 'basic',
    titleKey: 'pricing.basic.title',
    speed: '2 Mbps',
    priceKey: 'pricing.basic.price',
    featuresKeys: [
      'pricing.feature.1',
      'pricing.feature.2',
      'pricing.feature.3',
      'pricing.feature.4',
    ],
    isPopular: false,
  },
  {
    id: 'essential',
    titleKey: 'pricing.essential.title',
    speed: '3 Mbps',
    priceKey: 'pricing.essential.price',
    featuresKeys: [
      'pricing.feature.1',
      'pricing.feature.2',
      'pricing.feature.3',
      'pricing.feature.4',
    ],
    isPopular: false,
  },
  {
    id: 'family',
    titleKey: 'pricing.family.title',
    speed: '4 Mbps',
    priceKey: 'pricing.family.price',
    featuresKeys: [
      'pricing.feature.1',
      'pricing.feature.2',
      'pricing.feature.3',
      'pricing.feature.4',
    ],
    isPopular: true,
  },
  {
    id: 'pro',
    titleKey: 'pricing.pro.title',
    speed: '6 Mbps',
    priceKey: 'pricing.pro.price',
    featuresKeys: [
      'pricing.feature.1',
      'pricing.feature.2',
      'pricing.feature.3',
      'pricing.feature.4',
    ],
    isPopular: false,
  },
  {
    id: 'business',
    titleKey: 'pricing.business.title',
    speed: '8 Mbps',
    priceKey: 'pricing.business.price',
    featuresKeys: [
      'pricing.feature.1',
      'pricing.feature.2',
      'pricing.feature.3',
      'pricing.feature.4',
    ],
    isPopular: false,
  },
  {
    id: 'enterprise',
    titleKey: 'pricing.enterprise.title',
    speed: '10 Mbps',
    priceKey: 'pricing.enterprise.price',
    featuresKeys: [
      'pricing.feature.1',
      'pricing.feature.2',
      'pricing.feature.3',
      'pricing.feature.4',
    ],
    isPopular: false,
  },
];
